#+startup: showall
#+options: toc:nil ^:{}
#+property: header-args :eval no-export
#+begin_export html
---
title:  "Spooky Security"
author: Eric Bailey
tags: darwin, keyboard, security, skhd, chunkwm
---
#+end_export

*Update (21 September, 2018)*: It turns out [[https://github.com/keybase/client][Keybase.app]] was to blame. I've since
quit it and removed it from my login items, and all is well again.  This
[[https://github.com/koekeishiya/skhd/issues/48][skhd issue thread]] details some excellent debugging strategies, which I've
modified slightly here.

#+begin_src sh
ioreg -lw 0 \
    | perl -nle 'print $1 if /"kCGSSessionSecureInputPID"=(\d+)/' \
    | uniq \
    | xargs ps -o comm= -p
#+end_src

For example, when I enable secure keyboard entry in ~Terminal.app~, I see the
following output.

#+begin_example
/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
#+end_example

--------------------------------------------------------------------------------

I've been using [[https://koekeishiya.github.io/chunkwm/][chunkwm]] and [[https://github.com/koekeishiya/skhd][skhd]] to help make Darwin more palatable, but ~skhd~
suddenly stopped working. When I try to start it manually, I get the following
error.

#+begin_example
skhd: secure keyboard entry is enabled! abort..
#+end_example

[[https://github.com/koekeishiya/skhd/issues/48][The internet suggested]] I disable [[https://iterm2.com/][iTerm 2]]'s /Secure Keyboard Entry/, but I've
switched to [[https://sw.kovidgoyal.net/kitty/][kitty]].

After some further frantic [[https://duckduckgo.com/][DuckDuckGo]]-ing, I came across a function,
=DisableSecureEventInput=, which seemed like the answer, so I wrote a quick
program to call it and try to end my troubles.

#+begin_src c :tangle ../../hakyll/code/fix-skhd.c
#include <Carbon/Carbon.h>


int main(int argc, const char *argv[])
{
    if (IsSecureEventInputEnabled())
	printf("Secure keyboard entry is enabled.\n");

    DisableSecureEventInput();

    if (IsSecureEventInputEnabled())
	printf("Secure keyboard entry is still enabled.\n");


    return 0;
}
#+end_src

#+begin_src sh :exports results :results output :dir ../../hakyll/code
/usr/bin/gcc -framework Carbon -o fix-skhd ./fix-skhd.c
./fix-skhd
#+end_src

#+results:
: Secure keyboard entry is enabled.
: Secure keyboard entry is still enabled.

No such luck. I'm [[https://www.youtube.com/watch?v%3DqjGjuiFKE04][literally dying]].
