#+OPTIONS: toc:nil
#+BEGIN_EXPORT html
---
title:  "Matching strings in LFE patterns"
author: Eric Bailey
tags: lfe, lisp, beam, pattern-matching, open-source
---
#+END_EXPORT

While writing an LFE solution for [[http://adventofcode.com/day/6][Day 6 of Advent of Code]], I found myself
wanting to write ~parse_instruction/1~ like this:
#+BEGIN_SRC erlang
parse_instruction("toggle " ++ Rest) -> toggle(parse_coordinates(Rest));
parse_instruction("turn on " ++ Rest) -> turn_on(parse_coordinates(Rest));
parse_instruction("turn off " ++ Rest) -> turn_off(parse_coordinates(Rest)).

parse_coordinates(String) ->
  {ok,[X0,Y0,X1,Y2],[]} = io_lib:fread("~d,~d through ~d,~d", String),
  {{X0,Y0},{X1,Y1}}.

toggle({{X0,Y0},{X1,Y1}}) -> undefined.
turn_on({{X0,Y0},{X1,Y1}}) -> undefined.
turn_off({{X0,Y0},{X1,Y1}}) -> undefined.
#+END_SRC

But the literal LFE translation [[https://github.com/rvirding/lfe/issues/176][doesn't work as desired]].
#+BEGIN_SRC lfe
(defun parse-instruction
  ([(++ "turn off " rest)]
   ...))
#+END_SRC

Instead, invocation of a ~defun~ of that form throws a =function_clause= error.
#+BEGIN_SRC lfe :exports code
> (defun f ([(++ "prefix" suffix)] suffix))
f
> (f "prefixsuffix")
exception error: function_clause
#+END_SRC

After this discovery, I took to [[http://webchat.freenode.net/?channels=erlang-lisp][#erlang-lisp]] and tried to figure out why.
Discussing the issue with =@rvirding= for a few minutes, we decided adding ~++*~
and having patterns like ~(++* "prefix" suffix)~ expand to nested ~cons~-es was
a solid approach.

N.B. In [[https://github.com/rvirding/lfe/releases/tag/v0.10.1][v0.10.1]], ~exp_append/1~ had the following [[https://github.com/rvirding/lfe/blob/v0.10.1/src/lfe_macro.erl#L911-L912][clause]], commented out.
#+BEGIN_SRC erlang
%% Cases with lists of numbers (strings).
[[N|Ns]|Es] when is_number(N) -> [cons,N,['++',Ns|Es]];
#+END_SRC

Rather than take the overly complicated approach of counting and limiting the
number of expanded ~cons~-es and bottoming out to a call to ~erlang:++~, we
decided to [[http://www.catb.org/jargon/html/K/KISS-Principle.html][keep it simple]] and just let ~++*~ patterns do their own thing.

The [[https://github.com/rvirding/lfe/compare/b867573e9d144988b5bc70bfe00aa08b27b3a7d6...a5d7c23ebd3005d4f9ff8714d8e02f06aa2d6abe][solution]] we came up with is as follows:
#+BEGIN_SRC erlang
%% exp_predef(...) -> ...;
exp_predef(['++*'|Abody], _, St) ->
  Exp = exp_prefix(Abody),
  {yes,Exp,St};
%% exp_predef(...) -> ....

exp_prefix([[N|Ns]|Es]) when is_number(N) -> [cons,N,['++*',Ns|Es]];
exp_prefix([[]|Es]) -> ['++*'|Es];
exp_prefix(Args) -> exp_append(Args).
#+END_SRC

Now in the [[https://github.com/rvirding/lfe/tree/develop][develop]] branch, you can do the following:
#+BEGIN_SRC lfe
> (defun f ([(++* "prefix" suffix)] suffix))
f
> (f "prefixsuffix")
"suffix"
#+END_SRC

or even:
#+BEGIN_SRC lfe
> (defun f ([(++* "p" "r" "e" "f" "i" "x" suffix)] suffix))
f
> (f "prefixsuffix")
"suffix"
#+END_SRC
