#+STARTUP: showall
#+OPTIONS: toc:nil ^:{}
#+BEGIN_EXPORT html
---
title:  "Bye Bye, Jekyll!"
author: Eric Bailey
tags: blogging, haskell, open-source
---
#+END_EXPORT

Back in December of 2014, I set up a blog using [[https://ghost.org][Ghost]] and [[https://github.com/axitkhurana/buster/][Buster]]. That was all
fine and good, but left quite a bit to be desired. I'm not a Python user and the
whole workflow was a bit too clunky for my taste.

# FIXME: obviously
#+BEGIN_EXPORT html
<p>
In July of 2015, I decided to migrate to
<a href="http://jekyllrb.com">Jekyll</a>.
It's pretty widely used and the integration with
<a href="https://pages.github.com">GitHub Pages</a> promised to be smooth and
easy.  In practice, I found its workflow to be similarly annoying. Worst of all,
it made me install, write and use Ruby.
<label for="sn-ruby-hater"
       class="margin-toggle">
&#8853;
</label>
<input type="checkbox"
       id="sn-ruby-hater"
       class="margin-toggle"/>
<span class="marginnote">
I'm a long-time Ruby hater. <a href="https://twitter.com/search?q=%2523sorrynotsorry">#sorrynotsorry</a>
</span>
</p>
#+END_EXPORT

What's more, GitHub seems to have a predilection for breaking things so often
and dramatically, that [[https://github.com/lfex/dragon][dragon]] was born.

[[http://haskellbook.com][Learning Haskell]] has been a [[https://www.youtube.com/watch?v=-1YjmXSyHa8][fantastic voyage]]. Although I've not yet used it for
any "real" projects, I'm sold on its expressivity and general
mind-expanding-ness. I had seen [[https://jaspervdj.be/hakyll/][Hakyll]] pop up on my radar a few times and
considered migrating to it for quite a while. Last night, I finally made the
leap. The experience was so great, I can't believe I didn't do it sooner.

#+BEGIN_EXPORT html
<p>
From now on, my blog will be powered by
<a href="https://jaspervdj.be/hakyll/">Hakyll</a>.
<label for="sn-dragon"
       class="margin-toggle">
&#8853;
</label>
<input type="checkbox"
       id="sn-dragon"
       class="margin-toggle"/>
<span class="marginnote">
... at least until <a href="https://github.com/lfex/dragon">dragon</a> matures,
or I find an even better alternative.
</span>
You can find my
<a href="https://github.com/yurrriq/blorg/blob/master/hakyll/site.hs">
<code>site.hs</code></a>, which will undoubtedly grow and change over time, on
<a href="https://github.com/yurrriq/blorg">GitHub</a>.
</p>

#+END_EXPORT
Good riddance.
