#+STARTUP: showall
#+OPTIONS: toc:nil ^:{}
#+BEGIN_EXPORT html
---
title: "Strange Mathematics"
author: Eric Bailey
date: 2020-08-02
tags: mathematics, proof, comics
---
#+END_EXPORT

On the first page of [[https://www.dccomics.com/talent/tom-king][Tom King]]'s [[https://www.dccomics.com/comics/strange-adventures-2020/strange-adventures-2][Strange Adventures #2]]
there is an example of [[https://reddit.com/r/badmathematics][bad mathematics]].

[[https://dc.fandom.com/wiki/T-Spheres][T-Sphere]]:
#+BEGIN_QUOTE
IN THE EQUATION
X² + MX + N = 0,
M AND N ARE INTEGERS.
THE ONLY POSSIBLE VALUE
OF X IS -3. WHAT IS THE
VALUE OF M?
#+END_QUOTE

[[https://dc.fandom.com/wiki/Michael_Holt_(New_Earth)][Mister Terrific]]:
#+BEGIN_QUOTE
SIX.
#+END_QUOTE

[[https://dc.fandom.com/wiki/T-Spheres][T-Sphere]]:
#+BEGIN_QUOTE
CORRECT.
#+END_QUOTE

But that's not quite right, or at least it's misleading.
While $6$ is a possible value for $m$, it's not the only one.

*Lemma*. Given $x^2 + mx + n = 0$ and $x = -3$,
there are [[https://brilliant.org/wiki/cardinality/][countably infinite]] possible values for $m$ such that
$m,n \in \mathbb{Z}$.

/Proof./
Rewriting the original equation with $x = -3$,
$9 - 3m + n = 0 \leadsto m = \frac{n}{3} + 3$.
It follows that $\forall m \in \mathbb{Z}, \exists n \in 3\mathbb{Z}$ such that
$m = \frac{n}{3} + 3$.
Since $3\mathbb{Z} \subset \mathbb{Z}$, and
there exists a bijection between $\mathbb{N}$ and $3\mathbb{Z}$, i.e.
$\{1,2,3,4,5,6,...\} \longleftrightarrow \{0,3,-3,6,-6,9,...\}$,
there are $\aleph_{0}$ possible values for $m$.
$\blacksquare$
